// <auto-generated />
namespace eInvoicing.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1at : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1at));
        
        string IMigrationMetadata.Id
        {
            get { return "202108241150195_1at"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
