// <auto-generated />
namespace eInvoicing.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1st_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1st_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202112201708383_1st_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
